# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - MavericsTodoList

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Ensure this matches your desired Node.js version

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: toDoList # <--- ADDED/CORRECTED THIS LINE

      - name: Zip artifact for deployment
        # This zips the contents of the 'toDoList' directory.
        run: zip release.zip ./toDoList -r # <--- UPDATED ZIP COMMAND
        # The working-directory for this step is still the repository root.
        # We specify './toDoList' to ensure only the app's contents are zipped.

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_851806C4AFE64676851F11720AE85CE8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_09AB3D1A6F40482DAA4B975932A12754 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C28820D76A8948DBA705C27C20B9D210 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MavericsTodoList' # Ensure this matches your Azure Web App name
          slot-name: 'Production' # Or 'staging' if you use deployment slots
          package: . # This tells the action to deploy the contents of the current directory
